---

version: "3.9"

services:
  perlite:
    build:
        context: ./perlite
        # For some reason resolution fails while building the container
        # Might be related to my env.
        extra_hosts:
          - "pecl.php.net:104.236.228.160"
          - "dl-cdn.alpinelinux.org:151.101.2.132"
    image: tooa/perlite:latest
    restart: unless-stopped
    networks:
      - web
    environment:
      - HIDE_FOLDERS=Templates,attachments
      - NOTES_PATH=homelab
      - SHOW_TOC=true
      - HOME_FILE=Dashboard
      #- LINE_BREAKS=true
      #- ALLOWED_FILE_LINK_TYPES=pdf
      #- DISABLE_POP_HOVER=false
      #- FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      #- SITE_TITLE=Demo
      #- SITE_TYPE=article
      #- SITE_URL=
      #- SITE_IMAGE=
      #- SITE_DESC=
      #- SITE_NAME=
      #- SITE_TWITTER=
    volumes:
      - /opt/perlite/vaults/homelab-vault:/var/www/perlite/homelab:ro
  webserver:
    build:
        context: ./web
        # For some reason resolution fails while building the container
        # Might be related to my env.
        extra_hosts:
          - "pecl.php.net:104.236.228.160"
          - "dl-cdn.alpinelinux.org:151.101.2.132"
    image: tooa/perlite_web:stable
    restart: unless-stopped
    volumes_from: 
      - perlite       
    depends_on:
      - perlite
    networks:
      - web
    labels:
      - "traefik.enable=true"

      # router
      - "traefik.http.routers.perlite.rule=Host(`vault.home.arpa`)"
      - "traefik.http.routers.perlite.entrypoints=websecure"
      - "traefik.http.routers.perlite.tls=true"

      # middleware
      - "traefik.http.routers.perlite.middlewares=authelia@docker,homer-cors"

networks:
  web:
    external: true